spring.data.mongodb.uri=mongodb+srv://developsumitkumar_db_user:x7XN4BvOxSq14uwe@cluster0.adxnyor.mongodb.net/kanbanboard?retryWrites=true&w=majority&appName=Cluster0

jwt.secret=mySecretKeyForKanbanboardApp2025ChangeThisInProduction
jwt.expiration=86400000

server.port=8080

spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

logging.level.com.example.kanbanboard=DEBUG
logging.level.org.springframework.security=DEBUG

spring.data.mongodb.auto-index-creation=true