spring.data.mongodb.host=cluster0.adxnyor.mongodb.net
spring.data.mongodb.port=27017
spring.data.mongodb.database=kanbanboard
spring.data.mongodb.username=developsumitkumar_db_user
spring.data.mongodb.password=x7XN4BvOxSq14uwe
spring.data.mongodb.authentication-database=admin

jwt.secret=mySecretKeyForKanbanboardApp2025ChangeThisInProduction
jwt.expiration=86400000

server.port=8080

spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

logging.level.com.example.kanbanboard=DEBUG
logging.level.org.springframework.security=DEBUG

spring.data.mongodb.auto-index-creation=true